<?php
/**
 * Shortcodes for the SaaS Dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class AMM_Shortcodes {

	public function __construct() {
		add_shortcode( 'amm_dashboard', array( $this, 'render_dashboard' ) );
		add_shortcode( 'amm_shared_intel', array( $this, 'render_shared_intel' ) );
	}

	public function render_shared_intel() {
		$id = (int)($_GET['id'] ?? 0);
		$post = get_post( $id );
		if ( ! $post || get_post_meta( $id, 'amm_is_public', true ) !== 'yes' ) {
			return '<p>Shared intelligence not found or private.</p>';
		}

		ob_start();
		?>
		<div class="amm-shared-view" style="font-family:serif; line-height:1.6; padding:50px; max-width:800px; margin:auto; background:#fff; border-radius:12px; box-shadow:0 10px 30px rgba(0,0,0,0.05);">
			<h1><?php echo esc_html($post->post_title); ?></h1>
			<p style="color:#888; border-bottom:1px solid #eee; padding-bottom:10px;">Generated by AI Multi-Mind Engine</p>
			<div style="white-space:pre-wrap; margin-top:30px;"><?php echo esc_html($post->post_content); ?></div>
			<div style="margin-top:50px; text-align:center;">
				<a href="<?php echo home_url(); ?>" class="button primary">Get your own AI Minds</a>
			</div>
		</div>
		<?php
		return ob_get_clean();
	}

	public function render_dashboard() {
		if ( ! is_user_logged_in() ) {
			return '<p>Please <a href="' . wp_login_url() . '">login</a> to access the AI Multi-Mind Engine.</p>';
		}

		ob_start();
		?>
		<div id="amm-onboarding-overlay" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.8); z-index:9999; align-items:center; justify-content:center;">
			<div class="amm-form-card" style="max-width:500px; text-align:center;">
				<h2>Welcome to AI Multi-Mind! 🚀</h2>
				<p>Ready to access the world's most elite business minds? Here is how to get started:</p>
				<ul style="text-align:left; margin:20px 0;">
					<li><strong>1. Select a Mind</strong>: Choose from 30+ specialized AI personas.</li>
					<li><strong>2. Define your Task</strong>: Use a template or write a custom request.</li>
					<li><strong>3. Ignite</strong>: Watch the engine build your strategy in real-time.</li>
				</ul>
				<button onclick="closeOnboarding()" class="amm-primary-btn">Start My Journey</button>
			</div>
		</div>

		<div id="amm-dashboard-root" class="amm-dashboard">
			<aside class="amm-app-sidebar">
				<div class="amm-logo">AI Multi-Mind</div>
				<div id="amm-user-profile" style="margin-bottom:20px; font-size:12px; color:#888;"></div>
				<nav class="amm-nav">
					<a href="#" class="amm-nav-item" data-tab="dashboard">📊 Dashboard</a>
					<a href="#" class="amm-nav-item active" data-tab="generate">🚀 Ignite Mind</a>
					<a href="#" class="amm-nav-item" data-tab="library">📚 Minds Library</a>
					<a href="#" class="amm-nav-item" data-tab="workspace">📁 My Workspace</a>
					<a href="#" class="amm-nav-item" data-tab="team">👥 Team Hub</a>
					<a href="#" class="amm-nav-item" data-tab="affiliate">💸 Affiliates</a>
					<a href="#" class="amm-nav-item" data-tab="billing">💳 Billing</a>
					<a href="#" class="amm-nav-item" data-tab="settings">⚙️ Settings</a>
				</nav>
				<div class="amm-user-block">
					<div id="amm-user-stats-sidebar">Loading stats...</div>
					<div class="amm-usage-bar-container" style="margin-top:10px; background:#ddd; height:8px; border-radius:4px; overflow:hidden;">
						<div id="amm-usage-bar" style="background:#007cba; height:100%; width:0%; transition:width 0.5s;"></div>
					</div>
					<button id="amm-theme-toggle" class="amm-theme-btn">🌓 Toggle Mode</button>
				</div>
			</aside>

			<main class="amm-app-content">
				<!-- Dashboard Tab -->
				<section id="tab-dashboard" class="amm-tab-content">
					<h2>Elite Insights</h2>
					<div class="amm-grid-layout" style="margin-top:20px;">
						<div class="amm-form-card">
							<strong>Total Strategies Generated</strong><br>
							<span id="amm-insight-gens" style="font-size:32px; color:#007cba;">0</span>
							<div style="background:#eee; height:10px; margin-top:10px; border-radius:5px;">
								<div id="amm-insight-gens-bar" style="background:#007cba; height:100%; width:0%; border-radius:5px;"></div>
							</div>
						</div>
						<div class="amm-form-card">
							<strong>Referral Network</strong><br>
							<span id="amm-insight-refs" style="font-size:32px; color:#007cba;">0</span>
						</div>
					</div>
				</section>

				<!-- Generate Tab -->
				<section id="tab-generate" class="amm-tab-content active">
					<header class="amm-tab-header">
						<h2>Generate Elite Strategy</h2>
						<p>Select a mind and an output type to begin the thinking process.</p>
					</header>
					<div class="amm-generate-layout">
						<div class="amm-controls">
							<label>Select Mind</label>
							<select id="amm-mind-select"><option value="">Loading minds...</option></select>
							<label>Output Type</label>
							<select id="amm-type-select">
								<option value="business_plan">Business Plan</option>
								<option value="marketing_plan">Marketing Plan</option>
								<option value="sales_script">Sales Script</option>
								<option value="sop">SOP</option>
								<option value="report">Business Report</option>
								<option value="blog_post">Blog Post</option>
								<option value="ad_copy">Ad Copy</option>
								<option value="video_script">Video Script</option>
							</select>
							<label>Output Language</label>
							<select id="amm-language-select">
								<option value="English">English</option>
								<option value="Spanish">Spanish</option>
								<option value="French">French</option>
								<option value="German">German</option>
								<option value="Portuguese">Portuguese</option>
								<option value="Italian">Italian</option>
							</select>
							<label>Task Template</label>
							<select id="amm-template-select">
								<option value="">Custom Request...</option>
								<option value="Create a $100M Grand Slam Offer for my service.">Grand Slam Offer ($100M)</option>
								<option value="Design a Blue Ocean strategy to dominate my local market.">Blue Ocean Strategy</option>
								<option value="Write an SOP for hiring and onboarding a new sales rep.">Sales Onboarding SOP</option>
								<option value="Draft a high-ticket sales script for a $5k coaching program.">High-Ticket Sales Script</option>
							</select>
							<textarea id="amm-input" placeholder="Enter your context, goals, and constraints here..."></textarea>
							<button id="amm-generate-btn" class="amm-primary-btn">IGNITE ENGINE</button>
						</div>
						<div class="amm-output-container">
							<div class="amm-output-header">
								<h3>Generated Intelligence</h3>
								<button id="amm-export-btn" class="amm-secondary-btn" style="display:none;">📄 Export PDF</button>
							</div>
							<div id="amm-output" class="amm-output-box">The engine is waiting for your request...</div>
						</div>
					</div>
				</section>

				<!-- Library Tab -->
				<section id="tab-library" class="amm-tab-content">
					<div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;">
						<h2>AI Minds Library</h2>
						<select id="amm-category-filter" style="width:200px;">
							<option value="">All Categories</option>
						</select>
					</div>
					<div id="amm-marketplace-grid" class="amm-grid-layout">Loading library...</div>

					<div id="amm-builder-container" style="display:none; margin-top:40px;">
						<h3>Elite Mind & Template Builder (PRO)</h3>
						<div class="amm-form-card" style="margin-bottom:20px;">
							<strong>Custom Mind</strong>
							<input type="text" id="amm-new-mind-name" placeholder="Mind Name (e.g. Real Estate Guru)">
							<input type="text" id="amm-new-mind-role" placeholder="Role Description">
							<textarea id="amm-new-mind-prompt" placeholder="Hidden Prompt Engineering Layer (The 'Brain' of the mind)"></textarea>
							<button id="amm-create-mind-btn" class="amm-primary-btn">Create Custom Mind</button>
						</div>
						<div class="amm-form-card">
							<strong>Task Template</strong>
							<input type="text" id="amm-new-template-title" placeholder="Template Title (e.g. YouTube Script Pro)">
							<textarea id="amm-new-template-content" placeholder="The actual prompt instructions for this template..."></textarea>
							<button id="amm-create-template-btn" class="amm-secondary-btn">Create Template</button>
						</div>
					</div>
				</section>

				<!-- Workspace Tab -->
				<section id="tab-workspace" class="amm-tab-content">
					<div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;">
						<h2>My Workspace</h2>
						<div style="display:flex; gap:10px;">
							<input type="text" id="amm-workspace-search" placeholder="Search strategy..." style="padding:8px; border-radius:8px; border:1px solid #ddd; width:200px;">
							<button id="amm-bulk-delete-btn" class="amm-secondary-btn" style="background:#ff4444; color:#fff;">Delete Selected</button>
							<button id="amm-new-folder-btn" class="amm-secondary-btn">+ New Folder</button>
						</div>
					</div>
					<div id="amm-workspace-list" class="amm-form-card">Loading saved outputs...</div>
				</section>

				<!-- Team Tab -->
				<section id="tab-team" class="amm-tab-content">
					<h2>Team Collaboration Hub</h2>
					<div class="amm-form-card" style="margin-bottom:20px;">
						<h3>Invite Team Member</h3>
						<input type="email" id="amm-invite-email" placeholder="email@example.com" style="width:70%;">
						<button id="amm-invite-btn" class="amm-primary-btn" style="width:25%;">Invite</button>
					</div>

					<div id="amm-branding-container" class="amm-form-card" style="margin-bottom:20px; display:none;">
						<h3>Agency White-Labeling</h3>
						<label>Custom Logo URL</label>
						<input type="text" id="amm-branding-logo" style="width:100%; margin-bottom:10px;">
						<label>Primary Brand Color</label>
						<input type="color" id="amm-branding-color" style="width:100%; margin-bottom:10px;">
						<button id="amm-branding-btn" class="amm-secondary-btn">Apply Branding</button>
					</div>

					<div id="amm-team-list" class="amm-form-card" style="margin-bottom:20px;">No team members found.</div>

					<h3>Pending Invitations</h3>
					<div id="amm-invite-list" class="amm-form-card">No pending invites.</div>
				</section>

				<!-- Affiliate Tab -->
				<section id="tab-affiliate" class="amm-tab-content">
					<h2>Affiliate Program</h2>
					<div id="amm-affiliate-info" class="amm-form-card">Loading your data...</div>
				</section>

				<!-- Settings Tab -->
				<section id="tab-settings" class="amm-tab-content">
					<h2>User Settings</h2>
					<div class="amm-form-card">
						<label>External Webhook URL (Zapier/Make)</label>
						<input type="text" id="amm-set-webhook" placeholder="https://hooks.zapier.com/..." style="width:100%; margin-bottom:20px;">
						<label>Default AI Mind</label>
						<select id="amm-set-default-mind" style="width:100%; margin-bottom:20px;"></select>
						<label>Knowledge Base (Your Company Context)</label>
						<textarea id="amm-set-kb" placeholder="About my business, products, target audience..." style="width:100%; height:150px; margin-bottom:20px;"></textarea>
						<p><input type="checkbox" id="amm-set-alerts"> Enable 90% Credit Usage Email Alerts</p>
						<button id="amm-save-settings-btn" class="amm-primary-btn">Save Preferences</button>
					</div>
				</section>

				<!-- Billing Tab -->
				<section id="tab-billing" class="amm-tab-content">
					<h2>Plans & Subscription</h2>
					<div class="amm-billing-grid">
						<div class="amm-plan-card"><h4>Starter</h4><p>$19/mo</p><button onclick="ammCheckout('starter')" class="amm-primary-btn">Select</button></div>
						<div class="amm-plan-card featured"><h4>Pro</h4><p>$49/mo</p><button onclick="ammCheckout('pro')" class="amm-primary-btn">Select</button></div>
						<div class="amm-plan-card"><h4>Agency</h4><p>$199/mo</p><button onclick="ammCheckout('agency')" class="amm-primary-btn">Select</button></div>
					</div>
						<div class="amm-form-card" style="margin-top:20px; text-align:center;">
							<h3>Need more credits?</h3>
							<p>Buy 50 extra credits for just $10.</p>
							<button onclick="ammCheckout('topup_50')" class="amm-secondary-btn" style="width:200px;">Buy Top-up</button>
						</div>

						<div style="margin-top:40px;">
							<h3>Billing History</h3>
							<div id="amm-billing-history" class="amm-form-card">Loading history...</div>
						</div>
				</section>
			</main>
		</div>

		<script>
		document.addEventListener('DOMContentLoaded', function() {
			const apiRoot = '<?php echo esc_url_raw( rest_url( 'amm/v1' ) ); ?>';
			const nonce = '<?php echo wp_create_nonce("wp_rest"); ?>';

			// Tab Logic
			document.querySelectorAll('.amm-nav-item').forEach(item => {
				item.addEventListener('click', (e) => {
					e.preventDefault();
					document.querySelectorAll('.amm-nav-item').forEach(i => i.classList.remove('active'));
					document.querySelectorAll('.amm-tab-content').forEach(c => c.classList.remove('active'));
					item.classList.add('active');
					document.getElementById('tab-' + item.dataset.tab).classList.add('active');
				});
			});

			// Onboarding Logic
			window.closeOnboarding = function() {
				document.getElementById('amm-onboarding-overlay').style.display = 'none';
				localStorage.setItem('amm_onboarded', 'yes');
			};
			if (!localStorage.getItem('amm_onboarded')) {
				document.getElementById('amm-onboarding-overlay').style.display = 'flex';
			}

			// Theme Logic
			document.getElementById('amm-theme-toggle').addEventListener('click', () => {
				document.getElementById('amm-dashboard-root').classList.toggle('dark-mode');
			});

			// Template Logic
			document.getElementById('amm-template-select').addEventListener('change', (e) => {
				if(e.target.value) document.getElementById('amm-input').value = e.target.value;
			});

			// Fetch Data
			function initApp() {
				// User Stats
				fetch(apiRoot + '/user', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(data => {
						const used = data.usage.used;
						const limit = data.usage.limit;
						const pct = Math.min(100, (used / limit) * 100);

						document.getElementById('amm-user-profile').innerText = `Welcome, ${data.user_name}`;
						document.getElementById('amm-user-stats-sidebar').innerHTML = `<strong>${data.plan.toUpperCase()}</strong><br>${used}/${limit} credits`;
						document.getElementById('amm-usage-bar').style.width = pct + '%';

						if (data.plan === 'pro' || data.plan === 'agency') document.getElementById('amm-builder-container').style.display = 'block';
						if (data.plan === 'agency') document.getElementById('amm-branding-container').style.display = 'block';

						// Populate Settings
						document.getElementById('amm-set-webhook').value = data.settings.webhook_url || '';
						document.getElementById('amm-set-default-mind').value = data.settings.default_mind || 'ceo';
						document.getElementById('amm-set-kb').value = data.settings.knowledge_base || '';
						document.getElementById('amm-set-alerts').checked = data.settings.usage_alerts;

						// Populate Insights
						if (document.getElementById('amm-insight-gens')) {
							const gens = data.insights.total_generations;
							document.getElementById('amm-insight-gens').innerText = gens;
							document.getElementById('amm-insight-gens-bar').style.width = Math.min(100, (gens / 50) * 100) + '%';
							document.getElementById('amm-insight-refs').innerText = data.insights.referral_count;
						}
					});

				// Templates
				fetch(apiRoot + '/templates', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(templates => {
						if(templates.length) {
							const select = document.getElementById('amm-template-select');
							select.innerHTML += templates.map(t => `<option value="${t.content}" ${t.locked ? 'disabled' : ''}>${t.title}${t.locked ? ' (Locked)' : ''}</option>`).join('');
						}
					});

				// Minds
				fetch(apiRoot + '/minds', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(minds => {
						window.ammAllMinds = minds;
						const options = minds.map(m => `<option value="${m.id}">${m.name}</option>`).join('');
						document.getElementById('amm-mind-select').innerHTML = options;
						document.getElementById('amm-set-default-mind').innerHTML = options;

						const categories = [...new Set(minds.map(m => m.category).filter(Boolean))];
						document.getElementById('amm-category-filter').innerHTML += categories.map(c => `<option value="${c}">${c}</option>`).join('');

						renderMindGrid(minds);
					});

				function renderMindGrid(minds) {
					document.getElementById('amm-marketplace-grid').innerHTML = minds.map(m => `
						<div class="amm-plan-card ${m.premium ? 'premium' : ''}">
							<strong>${m.name}</strong>
							<p style="font-size:10px; color:#888;">${m.category || 'Core'}</p>
							<p>${m.premium ? 'Premium Mind' : 'Core Mind'}</p>
							<button class="amm-secondary-btn" onclick="document.getElementById('amm-mind-select').value='${m.id}'; document.querySelector('[data-tab=generate]').click();">Use Mind</button>
							${m.premium ? '<button class="amm-primary-btn" style="margin-top:10px; font-size:10px;" onclick="ammCheckout(\'pro\')">Upgrade to Unlock</button>' : ''}
						</div>
					`).join('');
				}

				document.getElementById('amm-category-filter').addEventListener('change', (e) => {
					const cat = e.target.value;
					const filtered = cat ? window.ammAllMinds.filter(m => m.category === cat) : window.ammAllMinds;
					renderMindGrid(filtered);
				});

				// Workspace
				fetch(apiRoot + '/outputs', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(outputs => {
						const workspaceList = document.getElementById('amm-workspace-list');
						if (!outputs.length) {
							workspaceList.innerHTML = 'No outputs saved.';
							return;
						}
						workspaceList.innerHTML = '<table style="width:100%; text-align:left;">' +
							'<tr><th><input type="checkbox" id="amm-select-all"></th><th>Date</th><th>Title</th><th>Actions</th></tr>' +
							outputs.map(o => `<tr><td><input type="checkbox" class="amm-out-check" value="${o.id}"></td><td>${o.date}</td><td>${o.title}</td><td><button class="amm-secondary-btn" onclick="alert(${JSON.stringify(o.content)})">View</button> <button class="amm-secondary-btn" onclick="ammShare(${o.id})">🔗 Share</button> <button class="amm-secondary-btn" onclick="ammFeedback(${o.id}, 'up')">👍</button><button class="amm-secondary-btn" onclick="ammFeedback(${o.id}, 'down')">👎</button></td></tr>`).join('') +
							'</table>';

						document.getElementById('amm-select-all').addEventListener('change', (e) => {
							document.querySelectorAll('.amm-out-check').forEach(c => c.checked = e.target.checked);
						});
					});

				// Team & Invites
				fetch(apiRoot + '/teams', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(teams => {
						if(teams.length) {
							window.ammActiveTeamId = teams[0].id;
							document.getElementById('amm-team-list').innerHTML = teams.map(t => `<div><strong>${t.team_name}</strong> (${t.role})</div>`).join('');

							// Fetch Invites
							fetch(apiRoot + '/pending-invites?team_id=' + teams[0].id, { headers: { 'X-WP-Nonce': nonce } })
								.then(res => res.json()).then(invites => {
									if(invites.length) {
										document.getElementById('amm-invite-list').innerHTML = invites.map(i => `<div>${i.email} <button class="amm-secondary-btn" onclick="ammRevokeInvite(${i.id})" style="background:#ff4444; color:#fff;">Revoke</button></div>`).join('');
									}
								});
						}
					});

				// Billing History
				fetch(apiRoot + '/billing-history', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(history => {
						const historyBox = document.getElementById('amm-billing-history');
						if (history.length === 0) {
							historyBox.innerHTML = 'No payment history found.';
							return;
						}
						historyBox.innerHTML = '<table style="width:100%">' +
							'<tr><th>Date</th><th>Plan</th><th>Gateway</th><th>Status</th></tr>' +
							history.map(h => `<tr><td>${h.created_at}</td><td>${h.plan_id.toUpperCase()}</td><td>${h.gateway}</td><td>${h.status}</td></tr>`).join('') +
							'</table>';
					});

				// Affiliate
				fetch(apiRoot + '/affiliate', { headers: { 'X-WP-Nonce': nonce } })
					.then(res => res.json()).then(data => {
						document.getElementById('amm-affiliate-info').innerHTML = `<p>Referral Link: <code>${data.link}</code></p><p>Earnings: $${data.commissions}</p>`;
					});
			}
			initApp();

			// Generate Logic (Typewriter Effect)
			const btn = document.getElementById('amm-generate-btn');
			const outputBox = document.getElementById('amm-output');

			btn.addEventListener('click', () => {
				btn.disabled = true;
				outputBox.innerText = "The mind is thinking...";

				fetch(apiRoot + '/generate', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({
						mind_id: document.getElementById('amm-mind-select').value,
						output_type: document.getElementById('amm-type-select').value,
						user_input: document.getElementById('amm-input').value,
						language: document.getElementById('amm-language-select').value
					})
				})
				.then(res => res.json())
				.then(data => {
					if(data.success) {
						outputBox.innerText = "";
						let i = 0;
						const text = data.content;
						const interval = setInterval(() => {
							outputBox.innerText += text[i];
							i++;
							if(i >= text.length) {
								clearInterval(interval);
								btn.disabled = false;
								document.getElementById('amm-export-btn').style.display = 'block';
							}
						}, 5);
					} else {
						outputBox.innerText = "Error: " + data.message;
						btn.disabled = false;
					}
				});
			});

			// Feedback Logic
			window.ammFeedback = function(id, rating) {
				fetch(apiRoot + '/feedback', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({ post_id: id, rating: rating })
				}).then(res => res.json()).then(data => { if(data.success) alert('Feedback recorded. Thank you!'); });
			};

			// Share Logic
			window.ammShare = function(id) {
				fetch(apiRoot + '/share', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({ post_id: id })
				})
				.then(res => res.json())
				.then(data => {
					if(data.is_public) {
						prompt('Public link copied to clipboard (Ctrl+C):', data.share_url);
					} else {
						alert('Intelligence marked as private.');
					}
				});
			};

			// Handle Search
			document.getElementById('amm-workspace-search').addEventListener('input', (e) => {
				const term = e.target.value.toLowerCase();
				document.querySelectorAll('#amm-workspace-list tr').forEach(tr => {
					if (tr.querySelector('th')) return;
					const title = tr.innerText.toLowerCase();
					tr.style.display = title.includes(term) ? '' : 'none';
				});
			});

			// Export PDF
			document.getElementById('amm-export-btn').addEventListener('click', () => {
				const win = window.open('', '_blank');
				win.document.write(`<html><body style="font-family:sans-serif; padding:50px;"><h1>AI Multi-Mind Output</h1><hr>${outputBox.innerText}</body></html>`);
				win.print();
			});
		});

			// Handle Bulk Delete
			document.getElementById('amm-bulk-delete-btn').addEventListener('click', () => {
				const ids = Array.from(document.querySelectorAll('.amm-out-check:checked')).map(c => c.value);
				if(ids.length === 0 || !confirm('Delete selected?')) return;

				fetch(apiRoot + '/bulk-action', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({ ids, action: 'delete' })
				}).then(res => res.json()).then(data => { if(data.success) refreshWorkspace(); });
			});

			// Handle New Folder
			document.getElementById('amm-new-folder-btn').addEventListener('click', () => {
				const name = prompt('Enter folder name:');
				if(!name) return;

				fetch(apiRoot + '/create-folder', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({ name })
				}).then(res => res.json()).then(data => {
					if(data.success) {
						alert('Folder Created!');
						refreshWorkspace();
					}
				});
			});

			// Handle Create Template
			if (document.getElementById('amm-create-template-btn')) {
				document.getElementById('amm-create-template-btn').addEventListener('click', () => {
					fetch(apiRoot + '/create-template', {
						method: 'POST',
						headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
						body: JSON.stringify({
							title: document.getElementById('amm-new-template-title').value,
							content: document.getElementById('amm-new-template-content').value
						})
					}).then(res => res.json()).then(data => { if(data.success) { alert('Template Created!'); location.reload(); } });
				});
			}

			// Handle Branding
			document.getElementById('amm-branding-btn').addEventListener('click', () => {
				fetch(apiRoot + '/update-branding', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({
						team_id: window.ammActiveTeamId,
						logo: document.getElementById('amm-branding-logo').value,
						color: document.getElementById('amm-branding-color').value
					})
				}).then(res => res.json()).then(data => { if(data.success) alert('Branding Updated!'); });
			});

			// Handle Revoke Invite
			window.ammRevokeInvite = function(id) {
				fetch(apiRoot + '/revoke-invite', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({ id })
				}).then(res => res.json()).then(data => { if(data.success) location.reload(); });
			};

			// Handle Invite
			document.getElementById('amm-invite-btn').addEventListener('click', () => {
				const email = document.getElementById('amm-invite-email').value;
				if(!email) return;

				fetch(apiRoot + '/invite', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({ team_id: window.ammActiveTeamId, email })
				}).then(res => res.json()).then(data => {
					if(data.success) {
						prompt('Invite link generated! Send this to your team member:', data.invite_url);
					}
				});
			});

			// Handle Save Settings
			document.getElementById('amm-save-settings-btn').addEventListener('click', () => {
				fetch(apiRoot + '/update-settings', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': nonce },
					body: JSON.stringify({
						webhook_url: document.getElementById('amm-set-webhook').value,
						default_mind: document.getElementById('amm-set-default-mind').value,
						knowledge_base: document.getElementById('amm-set-kb').value,
						usage_alerts: document.getElementById('amm-set-alerts').checked
					})
				}).then(res => res.json()).then(data => { if(data.success) alert('Settings Saved!'); });
			});
		});

		window.ammCheckout = function(planId) {
			fetch('<?php echo esc_url_raw( rest_url( 'amm/v1' ) ); ?>/checkout', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'X-WP-Nonce': '<?php echo wp_create_nonce("wp_rest"); ?>' },
				body: JSON.stringify({ plan_id: planId, gateway: 'stripe' })
			}).then(res => res.json()).then(data => { if(data.url) window.location.href = data.url; });
		};
		</script>

		<style>
		.amm-dashboard { display: grid; grid-template-columns: 260px 1fr; min-height: 800px; font-family: 'Inter', -apple-system, sans-serif; background: #fff; color: #333; border-radius: 16px; overflow: hidden; box-shadow: 0 20px 50px rgba(0,0,0,0.08); border: 1px solid #eee; }
		.amm-app-sidebar { background: #fcfcfc; border-right: 1px solid #f0f0f0; padding: 40px 25px; display: flex; flex-direction: column; }
		.amm-logo { font-size: 20px; font-weight: 800; color: #007cba; margin-bottom: 40px; text-transform: uppercase; letter-spacing: 1px; }
		.amm-nav { flex-grow: 1; }
		.amm-nav-item { display: block; padding: 12px 15px; color: #555; text-decoration: none; border-radius: 8px; margin-bottom: 5px; font-weight: 500; transition: 0.2s; }
		.amm-nav-item:hover, .amm-nav-item.active { background: #007cba; color: #fff; }
		.amm-app-content { padding: 40px; overflow-y: auto; background: #fff; }
		.amm-tab-content { display: none; }
		.amm-tab-content.active { display: block; }
		.amm-generate-layout { display: grid; grid-template-columns: 350px 1fr; gap: 30px; margin-top: 30px; }
		.amm-controls label { display: block; font-weight: 600; margin-bottom: 8px; font-size: 13px; color: #888; }
		.amm-controls select, .amm-controls textarea { width: 100%; margin-bottom: 20px; border: 1px solid #ddd; border-radius: 8px; padding: 12px; }
		.amm-controls textarea { height: 180px; }
		.amm-primary-btn { width: 100%; background: linear-gradient(135deg, #007cba 0%, #005a87 100%); color: #fff; border: none; padding: 16px; border-radius: 10px; font-weight: 700; cursor: pointer; box-shadow: 0 4px 15px rgba(0,124,186,0.2); transition: transform 0.2s; }
		.amm-primary-btn:hover { transform: translateY(-2px); }
		.amm-secondary-btn { background: #eee; border: none; padding: 8px 12px; border-radius: 6px; cursor: pointer; font-size: 12px; }
		.amm-output-box { background: #f9f9f9; border: 1px solid #eee; border-radius: 12px; padding: 25px; min-height: 400px; white-space: pre-wrap; line-height: 1.6; }
		.amm-grid-layout { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 20px; }
		.amm-plan-card { border: 1px solid #eee; padding: 20px; border-radius: 12px; text-align: center; background: #fff; }
		.amm-plan-card.premium { border-color: gold; box-shadow: 0 5px 15px rgba(255,215,0,0.1); }
		.amm-plan-card.featured { border: 2px solid #007cba; transform: scale(1.05); }
		.amm-form-card { background: #f9f9f9; padding: 25px; border-radius: 12px; border: 1px solid #eee; }
		.amm-user-block { margin-top: 20px; padding-top: 20px; border-top: 1px solid #eee; font-size: 13px; }
		.amm-theme-btn { margin-top: 15px; width: 100%; background: none; border: 1px solid #ddd; border-radius: 6px; padding: 8px; cursor: pointer; }

		/* Dark Mode */
		.dark-mode { background: #111; color: #eee; }
		.dark-mode .amm-app-sidebar { background: #1a1a1a; border-right-color: #333; }
		.dark-mode .amm-app-content { background: #111; }
		.dark-mode .amm-nav-item { color: #aaa; }
		.dark-mode .amm-output-box, .dark-mode .amm-form-card, .dark-mode .amm-plan-card { background: #1a1a1a; border-color: #333; color: #eee; }
		.dark-mode .amm-controls select, .dark-mode .amm-controls textarea { background: #222; border-color: #444; color: #eee; }
		</style>
		<?php
		return ob_get_clean();
	}
}
